<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="KurrentDB.Client" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Hosts\Api\Hosts.Api.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\EventStore.SqlServer\EventStore.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Hosts\Web\Hosts.Web.csproj">
      <Aliases>WebHost</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\..\src\Hosts\AdminConsole\Hosts.AdminConsole.csproj">
      <Aliases>AdminConsoleHost</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\TestInfrastructure\TestInfrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
