<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Domain.Abstractions\Domain.Abstractions.csproj" />
  </ItemGroup>
</Project>
