<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Infrastructure.Tests" />
    <InternalsVisibleTo Include="Projections.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Domain.Abstractions\Domain.Abstractions.csproj" />
  </ItemGroup>
</Project>
